DEPLOY_NEXT = "DEPLOY_NEXT"
DEPLOYED = "DEPLOYED"
DESTROY_NEXT = "DESTROY_NEXT"

STARTED = "STARTED"
CREATED = "CREATED"
COMPLETED = "COMPLETED"
FAILED = "FAILED"
SKIPPED = "SKIPPED"
DESTROYED = "DESTROYED"

RID_STATUS_OPTIONS = [
    DEPLOYED,
    DEPLOY_NEXT,
    DESTROY_NEXT,
    DESTROYED,
    FAILED,
    SKIPPED,
]
CSD_STATUS_OPTIONS = [CREATED, STARTED, COMPLETED, FAILED, DESTROYED]
CSED_STATUS_OPTIONS = [CREATED, STARTED, COMPLETED, FAILED, SKIPPED, DESTROYED]
